Login_Register/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register

app_name = 'Login_Register'

urlpatterns = [
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

StudBuddy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('saran/', include('kritiksaran.urls')),
    path('catatan/', include('catatan.urls')),
    path('playlist/', include('playlist.urls')),
    path('jadwalbelajar/', include('jadwalbelajar1.urls')),
    path('Login_Register/', include('Login_Register.urls')),
    path('profile/', include('User_Profile.urls')),
]

kritiksaran/urls.py
from django.urls import path

from . import views

app_name = 'kritiksaran'

urlpatterns = [
    path('', views.home, name='home'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutUs', views.aboutUs, name='aboutUs')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script><!-- Bootstrap cdn and css-->
        <!--CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="https://lh3.googleusercontent.com/5sDBb4bZq6FJZ6tDWLxJPcJN5V_02GLgZ5D9QPyiDMA8HRCCGNzcPnyzvexAq11bTATwMbTgdVnlOgt9u1kpiyIXTl3UM3c9EQN-LbWY-xiUaZXUq3y8wHozTUFlCKScycOVnjVDDA=s260-p-k">
    <title>StudBuddy</title>

    <!--Swiper.css-->
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">  
    {% block meta %}

    {% endblock meta %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="https://lh3.googleusercontent.com/5ArrbN5DqS5yEzGgLgKJIn6V4bwnjJivRAzNZnX1BteDBoKzGU2tDBmfXB08keBQEd4oVv4E6HiOMnuubdDP6PfyFjgpBq7afaI0VpdwE4EDReUNBJH4Krrix_6WvmlpZCTTNmUViQ=w2400">
    <img src="https://lh3.googleusercontent.com/5ArrbN5DqS5yEzGgLgKJIn6V4bwnjJivRAzNZnX1BteDBoKzGU2tDBmfXB08keBQEd4oVv4E6HiOMnuubdDP6PfyFjgpBq7afaI0VpdwE4EDReUNBJH4Krrix_6WvmlpZCTTNmUViQ=w2400" alt="logo" style="width:75px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="topnav-right">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">| Home |</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://drive.google.com/drive/folders/16UGY73U1JXQe4gRSu3lskQfNGpXriz-Q">| Link Belajar |</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/jadwalbelajar">| Jadwal Belajar |</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="/catatan">| Catatan Pelajaran |</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="/playlist">| Playlist Musik |</a>
                </li>
                <li class="nav-item" style="float:right">
                    <a class="nav-link" href="/aboutUs">| About Us |</a>
                </li>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"> | Hello, {{ user.username }} | </a>
                        </li>
                        <li>
                            <a class="nav-link" href="/profile">| My Desk |</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'Login_Register:logout' %}">| Logout |</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Login_Register:auth' %}">| Login |</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'Login_Register:register' %}">| Register |</a>
                        </li>
                    {% endif %}
                    </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <a style="z-index: 10;"type="button" class="btn btn-warning btn-circle btn-xl float" href="{% url 'kritiksaran:home'%}" role="button"><i class="material-icons logo">chat_bubble</i></i></a>
</body>

</html>